import { Geist, Geist_Mono } from "next/font/google"; // imports fonts
import "./globals.css"; // loads and applies global styles to the whole app

const geistSans = Geist({ // prepare Geist font with these settings
  variable: "--font-geist-sans", // create CSS var with this font
  subsets: ["latin"], // specify only latin for faster load and smaller file
});

const geistMono = Geist_Mono({ // font loader function
  variable: "--font-geist-mono", // names the variable
  subsets: ["latin"],
});

export const metadata = { // next.js looks for metadata and finds it here for custom metadata
  title: "Create Next App", // this is also a convention "metadata"
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { // RootLayout could be banana since Next.js cares about app/layout.js
  return ( 
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // gives access to our fonts from above
      > 
        {children} 
      </body> 
    </html>
  ); // the {children} part has it such that if we went to app/page/ then it would have Home inbetween the layout
}
